//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class pictures
    {
        public int Id { get; set; }
        public Nullable<int> idcategory { get; set; }
        public string picture_path { get; set; }
        public string thumbnail_path { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> punctuation { get; set; }
    
        public virtual categories categories1 { get; set; }
    }
}
